disabled_rules:
  - function_parameter_count
  - nesting
  - identifier_name
  - weak_delegate
  - trailing_comma
  - trailing_whitespace
opt_in_rules:
  - force_unwrapping
  - private_outlet
line_length: 150
type_body_length:
  warning: 300
  error: 400
excluded:
  - Carthage/
  - Frameworks/
